WebApp/Controllers/AutorController.cs
using Logic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System;
using System.Linq;
using WebApp.Extensions;
using WebApp.Models;

namespace WebApp.Controllers
{
    [Route("[controller]/[action]")]
    public class AutorController : Controller
    {
        private readonly ILogger<AutorController> _logger;

        public AutorController(ILogger<AutorController> logger)
        {
            _logger = logger;
        }

        [HttpGet]
        public IActionResult Get()
        {
            AutorModel model = new AutorModel();
            var list = new AutorLogic().Get();
            return View("List", list);
        }

        [HttpGet]
        public IActionResult Create()
        {
            AutorModel model = new AutorModel();
            model.Autor.IsNew = true;
            return View("Master", model);
        }

        [HttpGet]
        public IActionResult Update(int id)
        {
            AutorModel model = new AutorModel();
            model.Autor = new AutorLogic().Get(id);
            model.Autor.IsNew = false;
            model.ListLibros = new AutoresHasLibrosLogic().Table().Include(x => x.Libro.Editorial).Where(x => x.AutorId == id).Select(x => x.Libro).ToList(); 
            return View("Master", model);
        }

        [HttpGet]
        public IActionResult Remove(int id)
        {
            try
            {
                AutorModel model = new AutorModel();
                model.Autor = new AutorLogic().Get(id);
                new AutorLogic().Remove(model.Autor);
            }
            catch (Exception e)
            {
                ModelState.AddModelError("Error", e.GetFullErrorMessage());
            }
            return Get();
        }


        [HttpPost]
        public IActionResult Edit(AutorModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (model.Autor.IsNew)
                    {
                        model.Autor = new AutorLogic().Create(model.Autor);
                    }
                    else
                    {
                        model.Autor = new AutorLogic().Update(model.Autor);
                    }
                    return Update(model.Autor.Id);
                }
            }
            catch (Exception e)
            {
                ModelState.AddModelError("Error", e.GetFullErrorMessage());
            }
            
            return View("Master", model);
        }
    }
}

WebApp/Controllers/EditorialController.cs
using Logic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using WebApp.Extensions;
using WebApp.Models;

namespace WebApp.Controllers
{
    [Route("[controller]/[action]")]
    public class EditorialController : Controller
    {
        private readonly ILogger<EditorialController> _logger;

        public EditorialController(ILogger<EditorialController> logger)
        {
            _logger = logger;
        }

        [HttpGet]
        public IActionResult Get()
        {
            EditorialModel model = new EditorialModel();
            var list = new EditorialLogic().Get();
            return View("List", list);
        }

        [HttpGet]
        public IActionResult Create()
        {
            EditorialModel model = new EditorialModel();
            model.Editorial.IsNew = true;
            return View("Master", model);
        }

        [HttpGet]
        public IActionResult Update(int id)
        {
            EditorialModel model = new EditorialModel();
            model.Editorial = new EditorialLogic().Get(id);
            model.Editorial.IsNew = false;
            model.ListLibros = new LibroLogic().Get(x => x.EditorialId == id);
            return View("Master", model);
        }

        [HttpGet]
        public IActionResult Remove(int id)
        {
            try
            {
                EditorialModel model = new EditorialModel();
                model.Editorial = new EditorialLogic().Get(id);
                new EditorialLogic().Remove(model.Editorial);
            }
            catch (Exception e)
            {
                ModelState.AddModelError("Error", e.GetFullErrorMessage());
            }
            return Get();
        }


        [HttpPost]
        public IActionResult Edit(EditorialModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (model.Editorial.IsNew)
                    {
                        model.Editorial = new EditorialLogic().Create(model.Editorial);
                    }
                    else
                    {
                        model.Editorial = new EditorialLogic().Update(model.Editorial);
                    }
                    return Update(model.Editorial.Id);
                }
            }
            catch (Exception e)
            {
                ModelState.AddModelError("Error", e.GetFullErrorMessage());
            }
            
            return View("Master", model);
        }
    }
}

WebApp/Controllers/LibroController.cs
using Logic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using WebApp.Extensions;
using WebApp.Models;

namespace WebApp.Controllers
{
    [Route("[controller]/[action]")]
    public class LibroController : Controller
    {
        private readonly ILogger<LibroController> _logger;

        public LibroController(ILogger<LibroController> logger)
        {
            _logger = logger;
        }

        [HttpGet]
        public IActionResult Get()
        {
            LibroModel model = new LibroModel();
            var list = new LibroLogic().Get();
            return View("List", list);
        }

        [HttpGet]
        public IActionResult Create()
        {
            LibroModel model = new LibroModel();
            model.Libro.IsNew = true;
            model.ListEditoriales = new EditorialLogic().Get();
            return View("Master", model);
        }

        [HttpGet]
        public IActionResult Update(int id)
        {
            LibroModel model = new LibroModel();
            model.Libro = new LibroLogic().Get(id);
            model.Libro.IsNew = false;
            model.ListEditoriales = new EditorialLogic().Get();
            return View("Master", model);
        }

        [HttpGet]
        public IActionResult Remove(int id)
        {
            try
            {
                LibroModel model = new LibroModel();
                model.Libro = new LibroLogic().Get(id);
                new LibroLogic().Remove(model.Libro);
            }
            catch (Exception e)
            {
                ModelState.AddModelError("Error", e.GetFullErrorMessage());
            }
            return Get();
        }


        [HttpPost]
        public IActionResult Edit(LibroModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (model.Libro.IsNew)
                    {
                        model.Libro = new LibroLogic().Create(model.Libro);
                    }
                    else
                    {
                        model.Libro = new LibroLogic().Update(model.Libro);
                    }
                    return Update(model.Libro.Id);
                }
            }
            catch (Exception e)
            {
                ModelState.AddModelError("Error", e.GetFullErrorMessage());
            }

            return View("Master", model);
        }
    }
}

WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Travel</title>
    <link rel="stylesheet" href="~/lib/bootstrap-5.0.2-dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">Navbar</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item"><a class="nav-link" href="@Url.Action("Get","Autor")">Autores</a></li>
                        <li class="nav-item"><a class="nav-link" href="@Url.Action("Get","Editorial")">Editoriales</a></li>
                        <li class="nav-item"><a class="nav-link" href="@Url.Action("Get","Libro")">Libros</a></li>
                    </ul>
                </div>
            </div>
        </nav>
       
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Travel @*- <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>*@
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap-5.0.2-dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>